import type { Metadata, Viewport } from "next";
import "./globals.css";
import Providers from "@/contexts/Providers";
import { Toaster } from "@/components/ui/sonner";

export const viewport: Viewport = {
  userScalable: false,
  maximumScale: 1,
};

export const metadata: Metadata = {
  title: {
    absolute: "macOS",
    default: "macOS",
    template: "%s | macOS",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-dvw h-dvh min-w-dvw min-h-dvh fixed top-0 left-0 select-none`}
      >
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
